### ISSUE TITLE
Plugin mine

### ISSUE THREAD

**Issue by PocketMineDev** [manyDARK/LobbyCoreGUI#4]
I will reporter you on github since it is not your plugin but of BlawoHD, and if you do not write this to author I will let it strike, so think about what you are doing on GitHub and what plugins you overwrite, you have deleted the copyright what locking Audible. As NIHM it down or add as author BlawoHD because that's really not funny and I have da 100 files from the plugin and I created it but a spast had to overwrite it on being, even though it does not belong to fake developers!

**Comment by manyDARK** [comment]
give evidence... It's not your plugin. You do not have a lobby core plugin and there is no UI interface. Soo shut up thanks. Sorry for the answer!

**Comment by manyDARK** [comment]
What? New accound? "Joined Sept 17. 2018" gg
